import { Exercise } from "../models/exercise";

export const Exercises: Exercise[] = [
  { name: 'Alternate Dumbbell Power Snatch', videoUrl: 'https://www.youtube.com/embed/OktkfRlGcns' },
  { name: 'Alternating Dumbbell Hang Clean and Jerk', videoUrl: 'https://www.youtube.com/embed/ee0hJzll6wM' },
  { name: 'Bent Over Row' },
  { name: 'Burpee Over Dumbbell' },
  { name: 'Burpees' },
  { name: 'Butterfly Situps' },
  { name: 'Clean Pull', videoUrl: 'https://www.youtube.com/embed/vugfQJmjfK4' },
  { name: 'DB Goblet Squats', videoUrl: 'https://www.youtube.com/embed/a-dqF4NL2K4' },
  { name: 'Devil Press', videoUrl: 'https://www.youtube.com/embed/zlqEtAUds-I' },
  { name: 'Double Dumbbell Deadlift' },
  { name: 'Double Dumbbell Hang Snatch', videoUrl: 'https://www.youtube.com/embed/cSmvSLAiJUM' },
  { name: 'Double Under' },
  { name: 'Dual DB Clean and Press', videoUrl: 'https://www.youtube.com/embed/sQHS3A2g-M8' },
  { name: 'Dumbbell Clean', videoUrl: 'https://www.youtube.com/embed/n_JGhqgOA7w' },
  { name: 'Dumbbell Front Rack Hold', videoUrl: 'https://www.youtube.com/embed/gZ6PvaMEHU0' },
  { name: 'Dumbbell Front Squat' },
  { name: 'Dumbbell Hang Clean', videoUrl: 'https://www.youtube.com/embed/4w3nINKZA0E' },
  { name: 'Dumbbell Hang Clean High Pull', videoUrl: 'https://www.youtube.com/embed/I7MOBAOeZkA' },
  { name: 'Dumbbell Hang Power Clean', videoUrl: 'https://www.youtube.com/embed/myc1taX-uBs' },
  { name: 'Dumbbell Power Clean', videoUrl: 'https://www.youtube.com/embed/3PnWQwabq4Y' },
  { name: 'Dumbbell Power Clean And Jerk', videoUrl: 'https://www.youtube.com/embed/NfD4aS4qeEs' },
  { name: 'Dumbbell Push Press' },
  { name: 'Dumbbell Thruster', videoUrl: 'https://www.youtube.com/embed/VdPjfmRcQfw' },
  { name: 'Jumping Lunges' },
  { name: 'Man Maker', videoUrl: 'https://www.youtube.com/embed/2FrqzCeAjqM' },
  { name: 'Push Jerk', videoUrl: 'https://www.youtube.com/embed/VrHNJXoSyXw' },
  { name: 'Pushup' },
  { name: 'Renegade Row' },
  { name: 'Reverse Lunges' },
  { name: 'Shuttle Run' },
  { name: 'Squat Clean and Jerk', videoUrl: 'https://www.youtube.com/embed/PjY1rH4_MOA' },
  { name: 'Alternate Bicep Curl' },
  { name: 'Overhead Tricep Press' },
];

